resources:
 repositories:
   - repository: azure-test
     type: git
     name: java-azure-pipelines
     ref: main

trigger:
- test

pool:
  default

steps:
- checkout: self
  path: foo/workspace

- checkout: azure-test
  path: foo/test

- script: cd $(Pipeline.Workspace)/foo && ls -la

# - script: |
#     echo Hello, world!
#     echo "##vso[task.setvariable variable=TEST]'hello'"
#   displayName: 'Run a one-line script'

# - script: |
#     echo $TEST
#   displayName: 'Run a multi-line script'

# - script: |
#     chmod +x $(System.DefaultWorkingDirectory)/resources/setup.sh
#     $(System.DefaultWorkingDirectory)/resources/setup.sh     
#   displayName: 'Run a multi-line script'
