resources:
 repositories:
   - repository: azure-test
     type: git
     name: java-azure-pipelines
     ref: main

parameters:
- name: test
  displayName: Test
  type: string
  default: test-with-dashes
  values:
  - test-with-dashes
- name: doThing
  default: false 
  type: boolean

trigger:
- test

pool:
  default

steps:
- checkout: self
  path: foo/workspace

- checkout: azure-test
  path: foo/test

- script: cd $(Pipeline.Workspace)/foo && ls -la

- script: |
    echo Hello, world!
    echo "##vso[task.setvariable variable=TEST]'hello'"

    ANOTHER_TEST=$(echo ${{ parameters.test }} | cut -d "-" -f 3)

    echo $ANOTHER_TEST

- script: |
    echo "I am creepy"
  condition: and(succeeded(), 
                 eq('${{ parameters.doThing }}', 'true'),
                 eq(variables['Build.SourceBranch'], 'refs/heads/main'))

- task: DownloadSecureFile@1
  name: cert
  displayName: 'Download seila'
  inputs:
    secureFile: 'cert.crt'

- script: |
    cat $(cert.secureFilePath)

# - script: |
#     echo $TEST
#   displayName: 'Run a multi-line script'

# - script: |
#     chmod +x $(System.DefaultWorkingDirectory)/resources/setup.sh
#     $(System.DefaultWorkingDirectory)/resources/setup.sh     
#   displayName: 'Run a multi-line script'
