# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test

pool:
  default

steps:
- script: |
    echo Hello, world!
    echo "##vso[task.setvariable variable=TEST]'hello'"
  displayName: 'Run a one-line script'

- script: |
    echo $TEST
  displayName: 'Run a multi-line script'
