resources:
 repositories:
   - repository: azure-test
     type: git
     name: java-azure-pipelines
     ref: main

trigger:
- test

pool:
  default

steps:
- checkout: self
- script: |
    echo Hello, world!
    echo "##vso[task.setvariable variable=TEST]'hello'"
  displayName: 'Run a one-line script'

- script: |
    echo $TEST
  displayName: 'Run a multi-line script'

- script: |
    chmod +x $(System.DefaultWorkingDirectory)/resources/setup.sh
    $(System.DefaultWorkingDirectory)/resources/setup.sh     
  displayName: 'Run a multi-line script'
