resources:
 repositories:
   - repository: azure-test
     type: git
     name: java-azure-pipelines
     ref: main

parameters:
- name: test
  displayName: Test
  type: string
  default: test-with-dashes
  values:
  - test-with-dashes
- name: doThing
  default: false 
  type: boolean
  
variables:
- name: 'test'
  value: 'cert.crt'

trigger:
- test

pool:
  default

steps:
- checkout: self
  path: foo/workspace

- checkout: azure-test
  path: foo/test

- script: cd $(Pipeline.Workspace)/foo && ls -la

- script: |
    echo Hello, world!
    echo "##vso[task.setvariable variable=TEST]'hello'"

    ANOTHER_TEST=$(echo ${{ parameters.test }} | cut -d "-" -f 3)

    echo $ANOTHER_TEST

- script: |
    chmod +x $(Pipeline.Workspace)/foo/workspace/resources/setup.sh
    $(Pipeline.Workspace)/foo/workspace/resources/setup.sh     
  displayName: 'Run a multi-line script'
